default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: 5432

development:
  <<: *default
  database: c2s_notification_development

test:
  <<: *default
  database: c2s_notification_test

production:
  <<: *default
  database: c2s_notification_production
